{% set name = "quil" %}
{% set version = "0.21.6" %}

{% set py_version = "0.5.7" %}

package:
  name: quil-split
  version: {{ version }}

source:  # Upstream maintains different versions for these, however, the source code is the same  # The concern about maintaining separate recipes was a possible disconnect between the artifacts
  - url: https://github.com/rigetti/quil-rs/archive/refs/tags/quil-rs/v{{ version }}.tar.gz
    sha256: f34bccc8db959596bf3aa708683ba502157046d7ff58f38bbdcef05aa07cc8d7
    # patches:
    #   - fix-syrupy-dependent-test.patch  # Adding this to see if that triggers regro-cf-autotick-bot to update the recipe
  - url: https://github.com/rigetti/quil-rs/archive/refs/tags/quil-py/v{{ py_version }}.tar.gz
    sha256: de7899f51189122d1ea4e12f34206d931d1d6c2cfdeaafc77b5ae2422e5d43a8
    folder: unused-quil-py

build:
  number: 1

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin >=1.0.0,<2.0.0
    - python
  host:
    - python

outputs:
  - name: quil
    version: {{ py_version }}
    script: install-py.sh  # [unix]
    script: install-py.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('quil', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
      host:
        - pip
        - python
      run:
        - python
    test:
      imports:
        - quil
      source_files:
        - quil-py/test
      requires:
        - numpy
        - pytest
        - syrupy
      commands:
        - pytest quil-py/test

  - name: quil-py
    version: {{ py_version }}
    build:
      noarch: python
    requirements:
      run:
        - quil {{ py_version }}
    test:
      imports:
        - quil

  - name: quil_py
    version: {{ py_version }}
    build:
      noarch: python
    requirements:
      run:
        - quil {{ py_version }}
    test:
      imports:
        - quil

about:
  home: https://github.com/rigetti/quil-rs
  summary: 'Quil Parser & Program Builder'
  description: |
    The quil package provides tools for constructing, manipulating, parsing, and printing Quil programs.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://rigetti.github.io/quil-rs/quil.html

extra:
  recipe-maintainers:
    - MementoRC
