{% set name = "quil" %}
{% set version = "0.31.0" %}

{% set py_version = "0.16.0" %}
{% set cli_version = "0.8.0" %}

package:
  name: quil-split
  version: {{ version }}

source:
  - url: https://github.com/rigetti/quil-rs/archive/refs/tags/quil-rs/v{{ version }}.tar.gz
    sha256: 2eb2ff7b02a7b98e42c683779b0aff6b297c23f050cae31730f1e38430b38416
    folder: quil-root

  - url: https://github.com/rigetti/quil-rs/archive/refs/tags/quil-py/v{{ py_version }}.tar.gz
    sha256: 9d97af2579867f42054c383c886ced988c5a99297064355e211b6a5400c39882
    folder: quil-py
  - url: https://github.com/rigetti/quil-rs/archive/refs/tags/quil-cli/v{{ cli_version }}.tar.gz
    sha256: 3582fc352c364aff61431f36c37ff377fa6664a0b311faac47089a27fa95ea21
    folder: quil-cli

build:
  number: 1
  script_env:
    # Python 3.13 is newer than PyO3 0.20.x: try to force forward compatibility
    - PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1  # [py>=313]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.0.0,<2.0.0  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
  host:
    - maturin >=1.0.0,<2.0.0
    - python

outputs:
  - name: quil
    version: {{ py_version }}
    script: install-py.sh  # [unix]
    script: install-py.bat  # [win]
    build:
      ignore_run_exports:
        - python  # [build_platform != target_platform]
      run_exports:
        - {{ pin_subpackage('quil', max_pin='x.x') }}
      missing_dso_whitelist:
        - '*/ld64.so.2'  # [ppc64le]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - python  # [build_platform != target_platform]
      host:
        - maturin >=1.0.0,<2.0.0
        - pip
        - python
      run:
        - numpy
        - python
    test:
      imports:
        - quil
      source_files:
        - quil-py/quil-py/test
      requires:
        - pytest
        - syrupy
      commands:
        - pytest quil-py/quil-py/test

  - name: quil-py
    version: {{ py_version }}
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('quil', exact=True) }}
        - python
    test:
      imports:
        - quil

  - name: quil_py
    version: {{ py_version }}
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('quil', exact=True) }}
        - python
    test:
      imports:
        - quil

  - name: quil-cli
    version: {{ cli_version }}
    script: install-cli.sh  # [unix]
    script: install-cli.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - python  # [build_platform != target_platform]
      host:
        - maturin >=1.0.0,<2.0.0
        - pip
        - python
    test:
      commands:
        - quil-cli --help

  - name: quil_cli
    version: {{ cli_version }}
    requirements:
      run:
        - {{ pin_subpackage('quil-cli', exact=True) }}
    test:
      commands:
        - quil-cli --help

about:
  home: https://github.com/rigetti/quil-rs
  summary: 'Quil Parser & Program Builder'
  description: |
    The quil package provides tools for constructing, manipulating, parsing, and printing Quil programs.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://rigetti.github.io/quil-rs/quil.html

extra:
  recipe-maintainers:
    - MementoRC
