{% set name = "quil" %}
{% set version = "0.29.2" %}

{% set py_version = "0.13.1" %}
{% set cli_version = "0.6.1" %}

package:
  name: quil-split
  version: {{ version }}

source:
  - url: https://github.com/rigetti/quil-rs/archive/refs/tags/quil-rs/v{{ version }}.tar.gz
    sha256: c98874720ee1d573743081c5ad53e03367f2be4faaca656d536f91b1ed38a6e2
    folder: quil-root

  - url: https://github.com/rigetti/quil-rs/archive/refs/tags/quil-py/v{{ py_version }}.tar.gz
    sha256: ea7e05b18f4a27adfca3168b983e484b6ad672994600894ba1f3b70e0ed04d12
    folder: quil-py
  - url: https://github.com/rigetti/quil-rs/archive/refs/tags/quil-cli/v{{ cli_version }}.tar.gz
    sha256: 77761596f1690dcffd142235b5497028d8f3d08ce32ab469fbd93903269c5349
    folder: quil-cli

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.0.0,<2.0.0  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
  host:
    - maturin >=1.0.0,<2.0.0
    - python

outputs:
  - name: quil
    version: {{ py_version }}
    script: install-py.sh  # [unix]
    script: install-py.bat  # [win]
    build:
      ignore_run_exports:
        - python  # [build_platform != target_platform]
      run_exports:
        - {{ pin_subpackage('quil', max_pin='x.x') }}
      missing_dso_whitelist:
        - '*/ld64.so.2'  # [ppc64le]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - python  # [build_platform != target_platform]
      host:
        - maturin >=1.0.0,<2.0.0
        - pip
        - python
      run:
        - python
    test:
      imports:
        - quil
      source_files:
        - quil-py/quil-py/test
      requires:
        - numpy
        - pytest
        - syrupy
      commands:
        - pytest quil-py/quil-py/test

  - name: quil-py
    version: {{ py_version }}
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('quil', exact=True) }}
        - python
    test:
      imports:
        - quil

  - name: quil_py
    version: {{ py_version }}
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('quil', exact=True) }}
        - python
    test:
      imports:
        - quil

  - name: quil-cli
    version: {{ cli_version }}
    script: install-cli.sh  # [unix]
    script: install-cli.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - python  # [build_platform != target_platform]
      host:
        - maturin >=1.0.0,<2.0.0
        - pip
        - python
    test:
      commands:
        - quil-cli --help

  - name: quil_cli
    version: {{ cli_version }}
    requirements:
      run:
        - {{ pin_subpackage('quil-cli', exact=True) }}
    test:
      commands:
        - quil-cli --help

about:
  home: https://github.com/rigetti/quil-rs
  summary: 'Quil Parser & Program Builder'
  description: |
    The quil package provides tools for constructing, manipulating, parsing, and printing Quil programs.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://rigetti.github.io/quil-rs/quil.html

extra:
  recipe-maintainers:
    - MementoRC
