{% set name = "quil" %}
{% set version = "0.27.2" %}

{% set py_version = "0.11.3" %}
{% set cli_version = "0.4.2" %}

package:
  name: quil-split
  version: {{ version }}

source:
  - url: https://github.com/rigetti/quil-rs/archive/refs/tags/quil-rs/v{{ version }}.tar.gz
    sha256: 69e2cababa29ee7d1b511daebc13cf220e40fbcb1e3670b6e19c57b1e4debca6
    folder: quil-root
    patches:
      - fix-syrupy-dependent-test.patch

  - url: https://github.com/rigetti/quil-rs/archive/refs/tags/quil-py/v{{ py_version }}.tar.gz
    sha256: d53ad560e794feb17312a77cbcaab7f5f24b2e9e566d0c9d8d5621d27478c489
    folder: quil-py
    patches:
      - fix-syrupy-dependent-test.patch
  - url: https://github.com/rigetti/quil-rs/archive/refs/tags/quil-cli/v{{ cli_version }}.tar.gz
    sha256: 07c3289181e7527b5372f6b282508699bbeb68bbbf405d0176ec993f170dce10
    folder: quil-cli
    patches:
      - fix-syrupy-dependent-test.patch

build:
  number: 1
  script_env:
    # Python 3.13 is newer than PyO3 0.20.x: try to force forward compatibility
    - PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1  # [py>=313]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.0.0,<2.0.0  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
  host:
    - maturin >=1.0.0,<2.0.0
    - python

outputs:
  - name: quil
    version: {{ py_version }}
    script: install-py.sh  # [unix]
    script: install-py.bat  # [win]
    build:
      ignore_run_exports:
        - python  # [build_platform != target_platform]
      run_exports:
        - {{ pin_subpackage('quil', max_pin='x.x') }}
      missing_dso_whitelist:
        - '*/ld64.so.2'  # [ppc64le]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - maturin >=1.0.0,<2.0.0
        - python  # [build_platform != target_platform]
      host:
        - pip
        - python
      run:
        - python
    test:
      imports:
        - quil
      source_files:
        - quil-py/quil-py/test
      requires:
        - numpy
        - pytest
        - syrupy
      commands:
        - pytest quil-py/quil-py/test

  - name: quil-py
    version: {{ py_version }}
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('quil', exact=True) }}
        - python
    test:
      imports:
        - quil

  - name: quil_py
    version: {{ py_version }}
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('quil', exact=True) }}
        - python
    test:
      imports:
        - quil

  - name: quil-cli
    version: {{ cli_version }}
    script: install-cli.sh  # [unix]
    script: install-cli.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - python  # [build_platform != target_platform]
      host:
        - pip
        - maturin >=1.0.0,<2.0.0
        - python
    test:
      commands:
        - quil-cli --help

  - name: quil_cli
    version: {{ cli_version }}
    requirements:
      run:
        - {{ pin_subpackage('quil-cli', exact=True) }}
    test:
      commands:
        - quil-cli --help

about:
  home: https://github.com/rigetti/quil-rs
  summary: 'Quil Parser & Program Builder'
  description: |
    The quil package provides tools for constructing, manipulating, parsing, and printing Quil programs.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://rigetti.github.io/quil-rs/quil.html

extra:
  recipe-maintainers:
    - MementoRC
